### ISSUE TITLE
Semi-unrelated to this project, but it's affected: PlantUML online conversion not working

### ISSUE THREAD

**Issue by theinfra** [jawira/db-draw#17]
Just used the example code to generate the puml file succesfully but the part with the Jawira\PlantUmlClient\Client that uploads the output data into the url http://www.plantuml.com/plantuml/png/[DATA] is not working as it returns 403 HTTP Code. This is a problem with PlantUML's website, since when trying to use the online server functionality on the page (http://plantuml.com/plantuml) it returns the same 403 code when submitting our own code.

So you might want to remove that part from the example, or try some other service for online conversion if available

**Comment by jawira** [comment]
Thanks a lot for reaching me, but it seems the problem has been solved:

http://www.plantuml.com/plantuml/png/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
![png image](http://www.plantuml.com/plantuml/png/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000)

*** 

As an alternate solution you can [run your own server](https://plantuml.com/en/picoweb):

```console
$ plantuml -picoweb:8001
webPort=8001
```

Then use it like this: http://localhost:8001/plantuml/png/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

Picoweb server only generates svg and png images.

I'm closing the issue, thanks again :)
