### ISSUE TITLE
does it work for doctrine/dbal version 3.1.x?

### ISSUE THREAD

**Issue by S-Tian86** [jawira/db-draw#26]
When I try to install I have the following error:
```
jawira/db-draw[v1.2.0, ..., v1.2.3] require doctrine/dbal ^2.5 -> found doctrine/dbal[v2.5.0, ..., 2.13.5] 
but the package is fixed to 3.1.4 (lock file version) by a partial update and that version does not match. 
Make sure you list it as an argument for the update command.
```

thx.

**Comment by tourze** [comment]
Same problem.

**Comment by vladdnepr** [comment]
Hi. Can you add support of doctrine dbal 3?

**Comment by jawira** [comment]
Hello, I completely missed this thread, I will fix this month :)

**Comment by jawira** [comment]
@myselfhimself So this was like a pet project for me, I wasn't expecting complaints ;) give me some days, I will fix it this month :pray:

**Comment by jawira** [comment]
Done!

**Comment by myselfhimself** [comment]
Very big thanks for this, we now use your doctrine schema drawing tool to enrich our documentation from time to time!
Clever "pet project" ;) !
